export const CREATE_NOTICE_REQUEST = 'CREATE_NOTICE_REQUEST'
export const CREATE_NOTICE_SUCCESS = 'CREATE_NOTICE_SUCCESS'
export const CREATE_NOTICE_FAIL = 'CREATE_NOTICE_FAIL'

export const ALL_NOTICE_REQUEST = 'ALL_NOTICE_REQUEST'
export const ALL_NOTICE_SUCCESS = 'ALL_NOTICE_SUCCESS'
export const ALL_NOTICE_FAIL = 'ALL_NOTICE_FAIL'

export const NOTICE_DETAILS_REQUEST = 'NOTICE_DETAILS_REQUEST'
export const NOTICE_DETAILS_SUCCESS = 'NOTICE_DETAILS_SUCCESS'
export const NOTICE_DETAILS_FAIL = 'NOTICE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'